#数据源
spring:
  datasource:
    username: root
    password: 123456
#   url: jdbc:mysql://localhost:3306/gulimall_pms   在家没报时区的错误，在公司却有。解决方法：
#    在配置url的时候不能简单写成 ：
#    jdbc:mysql://localhost:3306/mybatis
#    而是要写成 ：
#    jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/gulimall_pms?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#扫描mapper文件
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #  为了不在每个类上配置主键策略，在这里统一配置主键自增
  global-config:
    db-config:
      id-type: auto

server:
  port: 10000